### ISSUE TITLE
Send email to provider other than GMail, ie Office365/Outlook

### ISSUE THREAD

**Issue by d-rankin** [xreef/EMailSender#14] opened 2021-04-12 23:17 UTC
As per the previous post, I am getting a similar error message when trying to use Office365 accounts (example@outlook.com, smtp.office365.com, port 587). I believe the equivalent to Less Secure Apps with Office365 is to use an App Password instead but I've not had any luck getting this to work. Are you able to verify this works with an Office365 account by any chance? Thanks.

Office365 settings:

Server name: smtp.office365.com
Port: 587
Encryption method: STARTTLS

code:

const char* email_login = "example@outlook.com";
  const char* email_password = "App Password";
  const char* email_from  = "example@outlook.com";
  const char* name_from = "MoistureSensor";
  const char* smtp_server = "smtp.office365.com";
//  const int* smtp_port = 587;  
  
    EMailSender emailSend(smtp_server, email_password, email_from, name_from, 587);

Error:

00:28:41.508 -> ..........................
00:28:47.274 -> Connection: ESTABLISHED
00:28:47.274 -> Got IP address: 192.168.0.117
00:29:07.887 -> Sending status: 
00:29:07.887 -> 0
00:29:07.887 -> 2
00:29:07.887 -> Could not connect to mail server

**Comment by xreef** [comment] 2021-04-13 20:44
Hi d-rankin,
I'm doing some fix on esp32, the error you have It's similar to the fixed one.
Please retry.
Bye Renzo

**Comment by d-rankin** [comment] 2021-04-16 19:45
Hey Renzo, 

Thanks for the reply. Unfortunately this is still happening with the same 'Could not connect to mail server' with the 2.4.2 update. I am using ESP8266 in case that makes any difference here, many thanks

**Comment by xreef** [comment] 2021-05-24 15:34
Hi d-rankin,
I try to check and the problem is that my library not support STARTTSL only SSL.
If I find a quite bit of time I'm going to implement It.
Bye Renzo

**Closed** 2021-05-30 21:19 UTC

**Comment by Andy2051** [comment] 2022-03-11 14:17
I am getting **exactly** the same, also running on an esp8266 (nodemcu):
```
Connection: ESTABLISHED
Got IP address: 192.168.0.113
Sending status: 
status=0
code=2
description=Could not connect to mail server
```
Email settings (as stated by my service provider):
```
Non-SSL Settings (NOT Recommended)
Username:	myemail@mydomain.org.uk
Password:	Use the email account’s password.
Incoming Server:	mail.mydomain.org.uk
IMAP Port: 143 POP3 Port: 110
Outgoing Server:	mail.mydomain.org.uk
SMTP Port: 587

```
Relevant code in the script
`EMailSender emailSend("myemail@mydomain.org.uk", "mypassword", "myemail@mydomain.org.uk", "myemail@mydomain.org.uk", "mail.mydomain.org.uk",587);`

I have spent nearly a day going round in circles on this.

**Comment by Andy2051** [comment] 2022-03-11 14:51
Cross posted, have it working with gmail, but see my edit.

**Comment by Andy2051** [comment] 2022-03-11 15:47
Sorted! Set up a gmail account for my oil tank sensor and set an app password. Not really what I wanted as I try and avoid anything google, but it works. 

Thanks for your efforts, I will now be able to email the tank reading daily, or if contents drop suddenly, send a warning email (given what is happening at the moment, central heating oil has doubled in price in the last two weeks = expect more theft :( ).

**Comment by xreef** [comment] 2022-03-11 15:50
Hehehehe.. I add a set of camera with a 3Km wifi antenna to prevent that.

Would you like to share your project?

**Comment by Andy2051** [comment] 2022-03-11 17:19
Still in progress! 

- esp8266 (nodemcu)
- Sensor sat on top of the tank (HC-SR04) - software done, that's the easy bit.
- wifi connection - software done.
- LittleFS - to store config files, e.g. SSIDs & pwds for wifi, and storing sensor readings. Previously used SPIFFS
- ftp server and client - to upload config files, download sensor readings to my NAS.
- webserver - so I can access it via my browser to see the current state, will be something similar to this:
[https://forums.linuxmint.com/viewtopic.php?p=2043719#p2043719](url)
a "weather station" I did about three years ago (my first, and to date only, arduino project also esp8266). "Borrowing" a lot from it.
- email, using your library.

Still doing the software, hardware will be battery powered (18650) with a solar panel for recharge. I'll probably have to put up an external POE access point. Started this when my current sensor failed and the supplier wants £250 for their latest model **and** they want a monthly subscription on top - no thank you!

My main problem is I'm not a fan of C++ and not fluent in it, normally use pascal, but not available for the Arduino.
[https://forums.linuxmint.com/viewtopic.php?p=2130761#p2130761](url) 
7,500 lines of code using the lazarus IDE.

**Comment by xreef** [comment] 2022-03-14 07:31
Hi @Andy2051,
It's very interesting, If you need some help you can write also on the site forum, and I try to support your project.

I develop a lot in the past with pascal, but now I think you must migrate to another language, the resource becomes limited.

I found it very simple to use (for the people that came from Delphi or VB) Java with https://www.eclipse.org/windowbuilder/ to create desktop applications.
Or NodeJS to create a web application (FE and BE).

Bye Renzo
